##################### Filebeat Confiruation - PAF #########################
#======================= Filebeat prospectors =============================
filebeat.prospectors:
- input_type: log
  paths:
    - "/var/log/capture/alerts-*.json"

fields:
  log.type: "paf_alerts"
  sensor_id: "SENSOR_CODE"
  client_id: "ORG_CODE"
fields_under_root: true


#================== Filebeat Global Options ===============================
filebeat.registry_file: /opt/sensor/conf/etc/registry/blu_paf

#========================= Filebeat modules ===============================
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 60s

#========================= Logstash output ===============================
output.logstash:
  bulk_max_size: 8192
  hosts: ["GC_IP:12106"]
  loadbalance: true
  worker: 5

logging.level: info
logging.to_files: true
logging.metrics.enabled: true
logging.metrics.period: 60s
logging.files:
  path: /var/log/filebeat/
  name: pafconn
  keepfiles: 7

close_inactive: 10s
scan_frequency: 60s

queue.mem:
  events: 4096
  flush.min_events: 512
  flush.timeout: 1s
