
################ Filebeat NAF Configuration Other Logs ###################
#====================== Filebeat prospectors =============================
filebeat.prospectors:
- input_type: log
  paths:
    - "/opt/zeek/logs/current/dhcp.log"

- input_type: log
  paths:
    - "/opt/zeek/logs/current/dns.log"

- input_type: log
  paths:
    - "/opt/zeek/logs/current/ftp.log"

- input_type: log
  paths:
    - "/opt/zeek/logs/current/http.log"

- input_type: log
  paths:
    - "/opt/zeek/logs/current/pe.log"

- input_type: log
  paths:
    - "/opt/zeek/logs/current/smtp.log"

- input_type: log
  paths:
    - "/opt/zeek/logs/current/software.log"

- input_type: log
  paths:
    - "/opt/zeek/logs/current/ssl.log"

- input_type: log
  paths:
    - "/opt/zeek/logs/current/dpd.log"

- input_type: log
  paths:
    - "/opt/zeek/logs/current/weird.log"

- input_type: log
  paths:
    - "/opt/zeek/logs/current/intel.log"

- input_type: log
  paths:
    - "/opt/zeek/logs/current/known_services.log"

- input_type: log
  paths:
    - "/opt/zeek/logs/current/notice.log"

- input_type: log
  paths:
    - "/opt/zeek/logs/current/reporter.log"

fields:
  log.type: "nbad"
  sensor_id: "SENSOR_CODE"
  client_id: "ORG_CODE"
fields_under_root: true


#================= Filebeat Global Options ===============================
filebeat.registry_file: /opt/sensor/conf/etc/registry/blu_nafh

#======================== Filebeat modules ===============================
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 60s

#========================= Logstash output ===============================
output.logstash:
  bulk_max_size: 8192
  hosts: ["GC_IP:12104"]
  timeout: 120
  loadbalance: true
  worker: 7

#================================ Logging =====================================
logging.level: info
logging.to_files: true
logging.metrics.enabled: true
logging.metrics.period: 60s
logging.files:
  path: /var/log/filebeat/
  name: nafrest
  keepfiles: 7

scan_frequency: 60s
queue.mem:
  events: 4096
  flush.min_events: 512
  flush.timeout: 1s










